### ISSUE TITLE
how to set title color in event view 

### ISSUE THREAD

**Issue by jo-me** [marksie1988/atomic-calendar-revive#227]
## Summary

I want to have different text colors in event view depending on the calendar the events originate from

**Expected behavior**

Text color based on color specified at calendar entity

**Actual behavior:**

Nothing

**Screenshots**

![image](https://user-images.githubusercontent.com/10351272/87921230-91d99c80-ca7a-11ea-8d1f-ec63cba57051.png)

**Card Configuration**

```
entities:
  - entity: calendar.gelber_sack_abholtermine
    titleColor: orange
  - entity: calendar.abfallwirtschaft_stuttgart
    titleColor: brown
maxDaysToShow: 7
showColors: true
showLoader: true
timeColor: darkgrey
title: Kalender
type: 'custom:atomic-calendar-revive'
name: Kalender

```

## Additional context

I'm migrating from the old atomic calendar to your component atm.
The old atomic calendar hat a titleColor attribute for each calendar entity.

According to docs and examples of your component:
- entities have a "color" option -> did not work in event view
- in quick start page the "titlecolor" setting is used => did not work

The global eventTitleColor setting works but is used for all events.

What is the right option?

Thanks

**Comment by marksie1988** [comment]
I have fixed this in version 2. 

It will hopefully be released by the end of the month, assuming I don't hit any issues.

**Comment by marksie1988** [comment]
Fixed in #237

**Comment by jo-me** [comment]
I've upgraded to 2.0 but I still can't get the colors to work in Event mode.
I've tried both "titleColor" and "color" attributes for each entity, but it is not used.

What is the correct way to configure this?

Thanks

**Comment by jo-me** [comment]
Figured it out:  it is called eventTitleColor

**Comment by jo-me** [comment]
After the last update it changed from `eventTitleColor: `to `color:`

**Comment by marksie1988** [comment]
@jo-me  
If you set `eventTitleColor` it will set the color of all events where the entity doesn't have `color` set
