### ISSUE TITLE
eventTitleColor not working as expected

### ISSUE THREAD

**Issue by kaizersoje** [marksie1988/atomic-calendar-revive#248]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of the following:
  - Checked the Quick Start documentation page and confirmed configuration is correct: <https://marksie1988.github.io/atomic-calendar-revive/quickstart.html> X
  - Checked the FAQs on documentation page for common solutions: <https://marksie1988.github.io/atomic-calendar-revive/faq.html> X
  - Checked that your issue isn't already filed: <https://github.com/marksie1988/atomic-calendar-revive/issues?q=is%3Aissue> X

### Describe the bug

`eventTitleColor` not working even though I have defined it in the configuration

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior**

`eventTitleColor` to be set to the color defined in the configuration

**Actual behavior:**

`eventTitleColor` not being set

**Screenshots**

**Card Configuration**

```yaml
- type: "custom:atomic-calendar-revive"
  name: "Home Calendar"
  entities:
  - entity: calendar.home_calendar
    icon: mdi:home
    color: 'GOLDENROD'
  - entity: calendar.aus_vic_public_holidays
    icon: mdi:calendar-star
    color: 'DEEPPINK'
  enableModeChange: true
  defaultMode: Event
  fullDayEventText: 'All day'
  untilText: 'Until'
  showColors: true
  maxDaysToShow: 7
  showLocation: true
  showMonth: false
  showCurrentEventLine: false
  dateColor: '#F8C471'
  dateSize: 110
  timeColor: WHEAT
  timeSize: 90
  eventTitleColor: gold
  nameColor: '#D4AC0D'
  eventTitleSize: 105
  locationIconColor: WHEAT
  locationLinkColor: LIGHTSALMON
  # locationTextSize: 90
  dimFinishedEvents: true
  finishedEventOpacity: 0.6
  finishedEventFilter: 'grayscale(100%)'
  # dayWrapperLineColor: black
  eventBarColor: TOMATO
  showProgressBar: true
  progressBarColor: TOMATO
```

### Versions

- HomeAssistant Version: 0.113.2
- Plugin Version: 2.0.0

**Comment by marksie1988** [comment]
Hey, 

I think that this is happening because you have set the `color` under each entity, this overrides the `eventTitleColor` setting

**Comment by chris-nite** [comment]
Unfortunately for me it isn't working as well anymore. Whatever i set up toggling "showColors" true/false, calendar own-colors set up to something, it seems nothing is changing anything.
My calendarcolor stays always the same based on the calendars own color in home assistant.
Thanks in advance.

**Comment by heyepic** [comment]
I'm having similar issues - mainly, my links are either blue/purple (visited). Before the update, they were white (which is what I wanted).

**Comment by marksie1988** [comment]
Ok thanks for the feedback ill take a look at it as soon as I can. 

Currently my test HA platform is broken so I'm building a new one which I can then take a look.

**Comment by marksie1988** [comment]
Ok I now see the same issue, no idea how I didnt spot this before release, must have introduced a bug 

I will start looking at this shortly and get a fix out

**Comment by marksie1988** [comment]
This is now resolved in #v2.0.1

**Comment by chris-nite** [comment]
Thanks for your fast response to this topic.
Unfortunately V2.0.1 and 2.1 doesn't seem to fix it for me. The colors and behavior are still the same.
This is my card-setup:
```
  - disableLocationLink: true
    entities:
      - entity: calendar.<firstcal>
      - entity: calendar.<secondcal>
      - entity: calendar.<thirdcal>
      - entity: calendar.contacts
    eventTitleColor: white
    fullDayEventText: Ganztägig
    maxDaysToShow: 3
    name: Bevorstehende Termin
    showColors: false
    showDate: false
    showLocation: true
    showWeekDay: true
    sortByStartTime: true
    type: 'custom:atomic-calendar-revive'
    untilText: Bis
```
Any ideas what might be wrong here?

**Comment by marksie1988** [comment]
Ok thanks I'll take another look at what's happening, however the best way to change the color would be to use Lovelace card mod and change the card with that. 

In future releases ice been considering removing the color options as they have issues like this.

**Comment by tomasrudh** [comment]
I can confirm that changing event title color using lovelace-card-mod works. I second the idea of moving from setting colors in this card and instead add classes and use lovelace-card-mod. Thanks for good work!

**Comment by marksie1988** [comment]
Great glad that works for you. And thanks for the feedback
